version: '3.3'
services:
  db:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - backend
  backend:
    container_name: "backend"
    build:
      context: app_backend/
      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
    depends_on:
      - db
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  frontend:
    build:
      context: app_frontend/
      dockerfile: Dockerfile
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: