version: '3'
services:
  db:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  backend:
    container_name: app-springboot-postgresql
    build:
      context: app_backend/
      dockerfile: Dockerfile.backend
    ports:
      - "9009:9009"
    depends_on:
      - db

  frontend:
    build:
      context: app_frontend/
      dockerfile: Dockerfile.frontend
    container_name: "frontend"
    ports:
      - "8082:80"
    depends_on:
      - backend
