server:
  port: 8080
spring:
  datasource:
    continue-on-error: true
    hikari:
      maximum-pool-size: 10
    initialization-mode: always
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/postgres?currentSchema=public
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false